version: "3"
services:
  hitch:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /app/docker/container_startup.sh
    volumes:
      - ../:/app
      - /app/docker
      - ./container_startup.sh:/app/docker/container_startup.sh
    ports:
      - "28292:28292"
    stdin_open: true
    tty: true