version: "3"
# Hitch
services:

  node_server:
    build:
      context: ./node_server
    entrypoint: /app/docker/node_server/container_startup.sh
    volumes:
      - ../NodeJs-Backend:/app
      - /app/docker
      - ./node_server/container_startup.sh:/app/docker/node_server/container_startup.sh
    links:
      - "mongodb"
    ports:
      - "8081:8081"
      - "25585:25585"
    stdin_open: true
    tty: true
  
  mongodb:
    build:
      context: ./mongodb
    entrypoint: /app/docker/mongodb/container_startup.sh
    volumes:
      - ./mongodb/container_startup.sh:/app/docker/mongodb/container_startup.sh
      - /Users/kyleblue/.mongodb/:/data/db/
      - /Users/kyleblue/.mongodb/log/:/var/log/
    ports:
      - "27017"
    stdin_open: true
    tty: true

  react_frontend:
    build:
      context: ./react_frontend
    entrypoint: /app/docker/react_frontend/container_startup.sh
    volumes:
      - ../React-Frontend:/app
      - /app/docker
      - ./react_frontend/container_startup.sh:/app/docker/react_frontend/container_startup.sh
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true